---
- hosts: MOODLE
  tasks:
  - name: apt-update
    become: yes
    become_method: sudo
    shell: "apt-get update"

  - name: install apache2
    become: yes
    become_method: sudo    
    apt: name=apache2 state=latest

  - name: install mysql
    become: yes
    become_method: sudo    
    apt: name=mysql-server state=latest

  - name: install php
    become: yes
    become_method: sudo    
    apt: name=php state=latest

  - name: install libapache2-mod-php
    become: yes
    become_method: sudo    
    apt: name=libapache2-mod-php state=latest

  - name: install php-mysql
    become: yes
    become_method: sudo    
    apt: name=php-mysql state=latest

  - name: install debconf-utils
    become: yes
    become_method: sudo    
    apt: name=debconf-utils state=latest

  - name: install php-mbstring
    become: yes
    become_method: sudo    
    apt: name=php-mbstring state=latest

  - name: install php-intl
    become: yes
    become_method: sudo    
    apt: name=php-intl state=latest

  - name: install php-soap
    become: yes
    become_method: sudo    
    apt: name=php-soap state=latest

  - name: install php-xml
    become: yes
    become_method: sudo    
    apt: name=php-xml state=latest

  - name: install php-xmlrpc
    become: yes
    become_method: sudo    
    apt: name=php-xmlrpc state=latest

  - name: install build-essential
    become: yes
    become_method: sudo    
    apt: name=build-essential state=latest

  - git:
      repo: 'https://git.in.moodle.com/moodle/moodle.git'
      dest: /tmp/moodle

  - git:
      repo: 'https://github.com/joomla/joomla-cms.git'
      dest: /tmp/joomla

  - name: cp moodle
    become: yes
    become_method: sudo
    shell: "cp -r /tmp/moodle /var/www"

  - name: cp joomla
    become: yes
    become_method: sudo
    shell: "cp -r /tmp/joomla /var/www"

  - name: copy info.php
    become: yes
    become_method: sudo
    copy: src=info.php dest=/var/www/joomla

  - name: copy info.php
    become: yes
    become_method: sudo
    copy: src=info.php dest=/var/www/moodle
 
  - name: passwd mysql
    copy: src=script.sql dest=/tmp/

  - name: mysql script
    become: yes
    become_method: sudo
    shell: "mysql </tmp/script.sql"

  - name: phpadmin script
    become: yes
    become_method: sudo
    copy: src=phpadmin.sh dest=/tmp/

  - name: php script
    become: yes
    become_method: sudo
    shell: "sh /tmp/phpadmin.sh"

  - name: install phpmyadmin
    become: yes
    become_method: sudo    
    apt: name=phpmyadmin state=latest

  - name: copy 000
    become: yes
    become_method: sudo
    copy: src=000-default.conf dest=/etc/apache2/sites-available

  - name: copy default
    become: yes
    become_method: sudo
    copy: src=default-ssl.conf dest=/etc/apache2/sites-available

  - name: copy ports.conf
    become: yes
    become_method: sudo
    copy: src=ports.conf dest=/etc/apache2/

  - name: a2ensite 000
    become: yes
    become_method: sudo
    shell: "a2ensite 000-default.conf"

  - name: a2ensite default
    become: yes
    become_method: sudo
    shell: "a2ensite default-ssl.conf"

  - name: restart apache2
    become: yes
    become_method: sudo
    shell: "systemctl restart apache2"

  - name: configuration.php
    become: yes
    become_method: sudo
    copy: src=configuration.php dest=/var/www/joomla
  
  - name: varmoodle
    become: yes
    become_method: sudo
    shell: "mkdir /var/www/moodledata"

  - name: change permission
    become: yes
    become_method: sudo
    shell: "chmod -R 777 /var/www/"

  - name: change permission
    become: yes
    become_method: sudo
    shell: "chmod -R 777 /var/www/moodledata"

  - name: copy crt
    become: yes
    become_method: sudo
    copy: src=amazonaws.com.crt dest=/etc/ssl/certs

  - name: copy key
    become: yes
    become_method: sudo
    copy: src=amazonaws.com.key dest=/etc/ssl/private

  - name: ssl
    become: yes
    become_method: sudo
    shell: "a2enmod ssl"
    
  - name: restart apache2
    become: yes
    become_method: sudo
    shell: "systemctl restart apache2"